### ISSUE TITLE
Mail VC doesn't show when crashing in application:didFinishLaunchingWithOptions:

### ISSUE THREAD

**Issue by lhunath** [kaler/CrashKit#2]
When the application crashes during application:didFinishLaunchingWithOptions:, the Mail view controller doesn't show.

Perhaps we can find a way to handle this situation as well to avoid missing crashes during start-up.

**Comment by kaler** [comment]
I would suggest using QuincyKit/HockeyKit or the TestFlight SDK.  They are much more featureful and maintained.
