### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by xdansmith** [kaler/CrashKit#3]
Is this project still being worked on, or has it been abandoned? I've been looking at different ways to capture crash reports for our iOS app.. We use ACRA on Android, and are looking for something similar for iOS... So far, I've found this project and PLCrashReporter.

Thanks,

Dan

**Comment by kaler** [comment]
Sorry Dan,

I haven’t updated this project in years.  You should use Testflight, Crashlytics, or HockeyApp/HockeyKit.  I believe Hockey is based on PLCrashReporter.
